sudo: required
language: generic
services:
- docker
env:
  matrix:
    - HHVM_VERSION=4.35.0
    - HHVM_VERSION=4.36.0
    - HHVM_VERSION=4.38.0
    - HHVM_VERSION=4.39.0
    - HHVM_VERSION=4.40.0
    - HHVM_VERSION=4.41.0
    - HHVM_VERSION=4.42.0
    - HHVM_VERSION=4.43.0
    - HHVM_VERSION=4.44.0
    - HHVM_VERSION=latest
install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
